---
- hosts: all
  become: yes
  become_user: root
  user: vagrant
  roles:
    - common
  # environment:
  #   https_proxy: "{{ lookup('env', 'https_proxy') }}"

- hosts: webservers
  become: yes
  become_user: root
  user: vagrant
  roles:
    - ubuntu1604
    - apache2
    - python2
    - pip
    - mod_wsgi
    - mysqlclient

- hosts: dbs
  become: yes
  become_user: root
  user: vagrant
  roles:
    - ubuntu1604
    - mysqlserver

# - import_playbook: ./common.yml
# - import_playbook: ./webservers.yml
# - import_playbook: ./dbs.yml
