---
- name: install libapache2-mod-wsgi
  apt: 
    name: libapache2-mod-wsgi
    state: present 

- name: set wsgi conf
  template: 
    src: /vagrant/playbook/roles/mod_wsgi/templates/wsgi.conf.j2 
    dest: /etc/apache2/mods-enabled/wsgi.conf
    owner: www-data
    group: www-data
    mode: 0744
  notify: restart_apache2

- apache2_module:
    name: wsgi
    state: present

