---
- name: add apt repository for installation python
  apt_repository:
    repo: ppa:jonathonf/python-2.7
    state: present
    update_cache: yes

- name: install build-essential
  become: yes
  apt: 
    name: build-essential
    state: present

- name: install checkinstall
  become: yes
  apt: 
    name: checkinstall
    state: present

- name: install libreadline-gplv2-dev
  become: yes
  apt: 
    name: libreadline-gplv2-dev
    state: present

- name: install libncursesw5-dev
  become: yes
  apt:
    name: libncursesw5-dev
    state: present

- name: install tk-dev
  become: yes
  apt:
    name: tk-dev
    state: present

- name: install libgdbm-dev
  become: yes
  apt: 
    name: libgdbm-dev
    state: present

- name: install libc6-dev
  become: yes
  apt: 
    name: libc6-dev
    state: present

- name: install packages gcc  
  become: yes
  apt: 
    name: gcc
    state: present

- name: install packages make  
  become: yes
  apt: 
    name: make
    state: present

- name: install packages openssl  
  become: yes
  apt: 
    name: openssl
    state: present

- name: install packages libsqlite3-dev  
  become: yes          
  apt: 
    name: libsqlite3-dev
    install_recommends: yes
    autoremove: yes
    state: present

- name: install packages libbz2-dev
  become: yes          
  apt: 
    name: libbz2-dev
    install_recommends: yes
    autoremove: yes
    state: present

- name: install packages libssl-dev
  become: yes
  apt:
    name: libssl-dev
    install_recommends: yes
    autoremove: yes
    state: present

- name: add bash_profile to vagrant
  file: 
    path: /home/vagrant/.bash_profile
    state: touch

- name: Install Python
  become: yes
  apt:
    name: python2.7=2.7.14-2ubuntu1~16.04.york0
    state: present

# install pip
- name: Download pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/src/
  become: yes

- name: install pip
  command: python /usr/src/get-pip.py
  become: yes