---

- name: install MySQL packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6
    - python-mysqldb

- name: set my.cnf
  template: 
    src: /vagrant/playbook/roles/mysqlserver/templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0777

- name: Start the MySQL service
  become: yes
  service: 
    name: mysql 
    state: started
    enabled: true

- name: create mysql user
  mysql_user: 
    name: "{{ mysql_user }}"
    host: "{{ item }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  with_items:
    - localhost
    - 192.168.20.10

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    name: all
    target: /vagrant/playbook/roles/mysqlserver/files/sample_db.sql
    