---
- hosts: dbs
  become: yes
  become_user: root
  user: vagrant

  vars:
    mysql_user: developer
    mysql_password: developer
  tasks:

    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: add apt repository for installation mysql
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu trusty universe
        state: present
        update_cache: yes

    - name: install MySQL packages
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
        - mysql-server-5.6
        - mysql-client-5.6
        - python-mysqldb

    # - name: set conf file
    #   mysql_variables:
    #     config_file: /home/vagrant/dbs/my.cnf

    - name: Start the MySQL service
      become: yes
      service: 
        name: mysql 
        state: started
        enabled: true

    - name: create mysql user
      mysql_user: 
        name: "{{ mysql_user }}"
        host: "{{ item }}"
        password: "{{ mysql_password }}"
        priv: '*.*:ALL,GRANT'
        state: present
      with_items:
        - localhost
        - 192.168.20.10

    - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
      mysql_db:
        state: import
        name: all
        target: /vagrant/dbs/sample_db.sql
        